# Generated by Django 4.1.4 on 2022-12-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
